language: node_js
node_js:
  - lts/*

script:
  - npm run coveralls
  - npm run doc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc
  target-branch: gh-pages
  on:
    branch: master
